name: Deploy JustTheDocs & Wasm Playground

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Compilar WebAssembly
        run: |
          mkdir -p web
          # Compilamos el binario para la web
          GOOS=js GOARCH=wasm go build -o web/main.wasm ./cmd/wasm
          # Copiamos el archivo puente que requiere Go para funcionar en el navegador
          cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/

      - name: Setup Ruby (Para Jekyll/JustTheDocs)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: './docs'

      - name: Construir JustTheDocs
        working-directory: './docs'
        run: |
          bundle install
          # Construimos el sitio y lo dejamos en la carpeta _site en la raíz
          bundle exec jekyll build -d ../_site

      - name: Unir Documentación con Playground Web
        run: |
          # Creamos la subcarpeta web dentro del sitio de la documentación
          mkdir -p _site/web
          # Movemos nuestra app web ahí adentro
          cp -r web/* _site/web/
          # Fundamental para que GitHub Pages no rompa nuestra app web
          touch _site/.nojekyll

      - name: Subir artefacto a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
